Bardellino/Controllers/ServizisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bardellino.Models;
using System.Web.Helpers;
using System.IO;
using System.Net.Mail;
using System.Threading.Tasks;

namespace Bardellino.Controllers
{
    public class ServizisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Servizis
        public ActionResult Index()
        {
            var servizi = db.Servizis.ToList();
            ViewBag.ServiziCount = servizi.Count();
            return View(servizi);
        }

        public ActionResult IndexUt()
        {
            if(User.Identity.Name == "cascinabardellino@gmail.com")
            {
            var servizi = db.Servizis.ToList();
             ViewBag.Servizi = servizi;
             return View(servizi);
          }
            else
            {
                var servizi = db.Servizis.Where(s => s.Pubblica == true).ToList();
                ViewBag.Servizi = servizi;
                return View(servizi);
            }
        }

        public ActionResult IndexUtMail(string servizio)
        {
            servizio = Request.QueryString["servizio"];
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> IndexUtMail(ServiziMailViewModels servizi, string servizio)
        {
            if (ModelState.IsValid)
            {
                MailMessage message = new MailMessage(
                    "webservice@cascinabardellino.it",
                    "cesare@cr-consult.eu, cascinabardellino@gmail.com",
                    "Richiesta informazioni dal sito cascinabardellino.it",
                    "Il giorno " + DateTime.Now + "<br/><strong>" +
                    servizi.Nome + " " +
                    servizi.Cognome + "</strong> [" +
                    servizi.Email + "] " +
                    "<br/> ha inviato una richiesta di informazioni dal sito www.cascinabardellino.it<hr/>Servizio: <strong>" +
                    servizio +
                    "</strong><br/>Testo del messaggio: <strong>" +
                    servizi.Messaggio +
                    "</strong></li>"
                    );
                message.IsBodyHtml = true;
                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                }
                return RedirectToAction("FormOk", "Home");
            }
            return View(servizi);
        }
        // GET: Servizis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servizi servizi = db.Servizis.Find(id);
            if (servizi == null)
            {
                return HttpNotFound();
            }
            return View(servizi);
        }

        // GET: Servizis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Servizis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Servizo_Id,Servizio,Pubblica", Exclude ="Descrizione")] Servizi servizi)
        {
            FormCollection collection = new FormCollection(Request.Unvalidated().Form);
            servizi.Descrizione = collection["Descrizione"];

            if (ModelState.IsValid)
            {
                db.Servizis.Add(servizi);
                db.SaveChanges();
                Directory.CreateDirectory(Server.MapPath("~/Content/Immagini/Servizi/" + servizi.Servizo_Id));
                return RedirectToAction("IndexUt");
            }

            return View(servizi);
        }

        // GET: Servizis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servizi servizi = db.Servizis.Find(id);
            if (servizi == null)
            {
                return HttpNotFound();
            }
            return View(servizi);
        }

        // POST: Servizis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Servizo_Id,Servizio,Pubblica", Exclude ="Descrizione")] Servizi servizi)
        {
            FormCollection collection = new FormCollection(Request.Unvalidated().Form);
            servizi.Descrizione = collection["Descrizione"];

            if (ModelState.IsValid)
            {
                db.Entry(servizi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexUt");
            }
            return View(servizi);
        }

        public ActionResult EditImg(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Servizi/" + id + "/"));
            ViewBag.Immagini = immagini.ToList();
            Servizi servizi = db.Servizis.Find(id);
            if (servizi == null)
            {
                return HttpNotFound();
            }
            return View(servizi);
        }

        [HttpPost]
        public ActionResult EditImg(IEnumerable<HttpPostedFileBase> files, int? id)
        {
            foreach (var file in files)
            {
                if (file != null)
                    try
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Immagini/Servizi/" + id + "/"), fileName);
                        WebImage img = new WebImage(file.InputStream);
                        var larghezza = img.Width;
                        var altezza = img.Height;
                        var rapportoO = larghezza / altezza;
                        var rapportoV = altezza / larghezza;
                        if (altezza > 1900 | larghezza > 1900)
                        {
                            if (rapportoO >= 1)
                            {
                                ViewBag.Message = "Attendi la fine del download...";
                                img.Resize(1900, 1900 / rapportoO);
                                img.Save(path);
                                ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                            }
                            else
                            {
                                ViewBag.Message = "Attendi la fine del download...";
                                img.Resize(800 / rapportoV, 800);
                                img.Save(path);
                                ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                            }
                        }
                        else
                        {
                            if (rapportoO >= 1)
                            {
                                ViewBag.Message = "Attendi la fine del download...";
                                img.Save(path);
                                ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                            }
                            else
                            {
                                ViewBag.Message = "Attendi la fine del download...";
                                img.Save(path);
                                ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
                    ViewBag.Message = "Devi scegliere un file";
                }
            }
            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Servizi/" + id + "/"));
            ViewBag.Immagini = immagini.ToList();
            Servizi servizi = db.Servizis.Find(id);
            if (servizi == null)
            {
                return HttpNotFound();
            }
            return View(servizi);

        }

        public ActionResult EditImgP(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Servizi/"));
            ViewBag.Immagini = immagini.ToList();
            Servizi servizi = db.Servizis.Find(id);
            if (servizi == null)
            {
                return HttpNotFound();
            }
            return View(servizi);
        }

        [HttpPost]
        public ActionResult EditImgP(HttpPostedFileBase file, int? id)
        {
            if (file != null)
                try
                {
                    var fileName = Path.GetFileName(file.FileName);

Bardellino/Views/Servizis/Create.cshtml
@model Bardellino.Models.Servizi

@{
    ViewBag.Title = "Create";
}
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

<h2>Crea nuovo servizio</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Servizio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Servizio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Servizio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descrizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descrizione, new { @class = "ckeditor" })
                @Html.ValidationMessageFor(model => model.Descrizione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pubblica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Pubblica)
                    @Html.ValidationMessageFor(model => model.Pubblica, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Annulla", "IndexUt", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

Bardellino/Views/Servizis/Delete.cshtml
@model Bardellino.Models.Servizi

@{
    ViewBag.Title = "Delete";
}

<h2>Cancella servizio</h2>

<h3>Sei sicuro di cancellare il servizio?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Servizio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Servizio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descrizione)
        </dt>

        <dd>
            @Html.Raw(Model.Descrizione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pubblica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pubblica)
        </dd>

    </dl>
    <hr/>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancella" class="btn btn-danger" />
            @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-success" })
        </div>
    }
</div>

Bardellino/Views/Servizis/DeleteImg.cshtml
@model Bardellino.Models.Servizi

@{
    ViewBag.Title = "DeleteImg";
}

<h2>Cancella immagine</h2>
<span class="galla2">
    <img src="@Url.Content("~/Content/Immagini/Servizi/" + Model.Servizo_Id + "/" + @ViewBag.File)" />

</span>
<hr />
<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="DeleteImg" class="btn btn-danger" />
            @Html.ActionLink("Annulla", "EditImg", "Servizis", new { id = Model.Servizo_Id }, new { @Class = "btn btn-primary" })
        </div>
    }
</div>

Bardellino/Views/Servizis/DeleteImgTot.cshtml
@{
    ViewBag.Title = "DeleteImgTot";
}

<h2>Cancella immagine</h2>
<h4>Questa immagine verrà definitivamente cancellata dal sito.</h4>
<hr />
<span class="galla">
    <img src="@Url.Content("~/Content/Immagini/Servizi/Tot/" + @ViewBag.File)" />

</span>
<hr />
<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancella" class="btn btn-danger" />
            @Html.ActionLink("Annulla", "EditImgTot", "Servizis", null, new { @Class = "btn btn-primary" })
        </div>
    }
</div>

Bardellino/Views/Servizis/EditImg.cshtml
@model Bardellino.Models.Servizi

@{
    ViewBag.Title = "EditImg";
}

<h2>Gestione immagini</h2>
<h4>
    Galleria fotografica <span class="badge">@Html.DisplayFor(model => model.Servizio)</span>
</h4><hr />
@using (Html.BeginForm("EditImg", "Servizis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="files" id="file" multiple />
    <p><span class="label label-success">Dimensione massima file o gruppo di file 4Mb</span></p>
    <h4><span class="label label-danger">@ViewBag.Message</span></h4>
    <input type="submit" value="Scarica immagine" class="btn btn-success" />
    @Html.ActionLink("Torna alla galleria", "Galleria", "Servizis", null, new { @class = "btn btn-primary" })
}
<hr />
<div class="galla1">
    @foreach (var item in ViewBag.Immagini)
    {
        var filename = Path.GetFileName(item);
        <div>
            <span>
                <a href="@Url.Content("~/Content/Immagini/Servizi/" + Html.DisplayFor(model => model.Servizo_Id) +"/" + @filename)" data-lightbox="example-set"><img src="@Url.Content("~/Content/Immagini/Servizi/" + Html.DisplayFor(model => model.Servizo_Id) +"/" + @filename)" alt="" /></a>
                <b><a href="@Url.Action("DeleteImg", "Servizis", new { id = Model.Servizo_Id, file = @filename})" title="Cancella immagine"> X </a></b>
            </span>
        </div>
    }

</div>

Bardellino/Views/Servizis/EditImgCel.cshtml
@{
    ViewBag.Title = "EditImgTot";
}

<h2>Gestione immagini cellulare</h2>
<h4>Galleria fotografica <span class="badge">generale</span></h4>
<hr />
@using (Html.BeginForm("EditImgCel", "Servizis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="files" id="file" multiple />
    <p><span class="label label-success">Dimensione massima file o gruppo di file 4Mb</span></p>
    <h4><span class="text-danger">@ViewBag.Message</span></h4>
    <button class="btn btn-primary" type="submit"><span class="fa fa-arrow-circle-down fa-4x"></span></button>
}
<hr />

Bardellino/Views/Servizis/EditImgP.cshtml
@model Bardellino.Models.Servizi

@{
    ViewBag.Title = "EditImgP";
}

<h2>Gestione immagini</h2>
<h4>
    Immagine logo <span class="badge">@Html.DisplayFor(model => model.Servizio)</span>
</h4><hr />
@using (Html.BeginForm("EditImgP", "Servizis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" id="file" />
    <p><span class="label label-success">Consigliata immagine quadrata 200x200</span></p>
    <h4><span class="label label-danger">@ViewBag.Message</span></h4>
    <input type="submit" value="Scarica immagne" class="btn btn-success" />
    @Html.ActionLink("Torna alla galleria", "IndexUt", "Servizis", new { @class="btn btn-primary"})
}
<hr />
<div class="row">
    <div class="col col-md-2 text-center">
        <span class="galla1">
            <a href="@Url.Content("~/Content/Immagini/Eventi/" + Model.Servizo_Id + ".jpg")" data-lightbox="example-set"><img class="example-image" src="@Url.Content("~/Content/Immagini/Servizi/" + Model.Servizo_Id + ".jpg")" /></a>
        </span>
    </div>
</div>

Bardellino/Views/Servizis/EditImgTot.cshtml
@{
    ViewBag.Title = "EditImgTot";
}

<h2>Gestione immagini</h2>
<h4>Galleria fotografica <span class="badge">generale</span></h4>
<hr />
@using (Html.BeginForm("EditImgTot", "Servizis", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="files" id="file" multiple />
    <p><span class="label label-success">Dimensione massima file o gruppo di file 4Mb</span></p>
    <h4><span class="label label-danger">@ViewBag.Message</span></h4>
    <input type="submit" value="Upload Image" class="btn btn-primary" />
}
<hr />
<div class="galla1">
    @foreach (var item in ViewBag.Immagini)
    {
        var filename = Path.GetFileName(item);
        <div >
            <span>
                <a href="@Url.Content("~/Content/Immagini/Servizi/Tot/" + @filename)" data-lightbox="example-set"><img src="@Url.Content("~/Content/Immagini/Servizi/Tot/" + @filename)" alt="" /></a>
                <b><a href="@Url.Action("DeleteImgTot", "Servizis", new {file = @filename})" title="Cancella immagine"> X </a></b>
            </span>
        </div>
    }

</div>
<h3>
    @Html.ActionLink(" ", "Index", null, new { @class = "glyphicon glyphicon-arrow-left" })
</h3>

Bardellino/Views/Servizis/Galleria.cshtml
@model IEnumerable<Bardellino.Models.Servizi>

@{
    ViewBag.Title = "Galleria";
}

@*Inizio galleria generale*@
<h2>Galleria
    @if(User.Identity.Name == "cascinabardellino@gmail.com")
    {
        <a href="@Url.Action("EditImgTot", "Servizis")" title="Aggiungi immagine"><span class="fa fa-plus-circle text-success"></span></a>
    }
    </h2>
<div class="galla1">
    @foreach (var tot in ViewBag.Immagini)
    {
        var filename = Path.GetFileName(tot);
            <div>
                <span>
                    <a href="@Url.Content("~/Content/Immagini/Servizi/Tot/" + @filename)" data-lightbox="example-set"><img src="@Url.Content("~/Content/Immagini/Servizi/Tot/" + @filename)" alt="" /></a>
                    @if (User.Identity.Name == "cascinabardellino@gmail.com")
                    {
                        <c><a href="@Url.Action("ImgRotateD", "Servizis", new { file = "Tot/" + @filename })" title="ruota immagine"> <span class="fa fa-undo"> </span> </a></c>
                        <b><a href="@Url.Action("DeleteImgTot", "Servizis", new {file = @filename })" title="Cancella immagine"> X </a></b>
                    }
                </span>
            </div>
    }
</div>
@*Fine galleria generale*@

@*Inizio galleria servizi*@
    @foreach (var item in Model)
    {
        <div>
            @{
                var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Servizi/" + item.Servizo_Id + "/")).ToList();
                if (User.Identity.Name == "cascinabardellino@gmail.com")
                {
                    <hr class="hr1" />
                    <span class="badge">@item.Servizio</span>
                        <a href="@Url.Action("EditImg", "Servizis", new {id = item.Servizo_Id })" title="Aggiungi immagine" class="h2"><span class="fa fa-plus-circle text-success"></span></a>
                    if (immagini.Count() > 0)
                    {
                        <div class="galla1">
                            @foreach (var immagine in immagini)
                            {
                                var filename = Path.GetFileName(immagine);
                                <div>
                                    <span>
                                        <a href="@Url.Content("~/Content/Immagini/Servizi/" + item.Servizo_Id + "/" + @filename)" data-lightbox="example-set"><img src="@Url.Content("~/Content/Immagini/Servizi/" + item.Servizo_Id +"/" + @filename)" alt="" /></a>
                                        @if (User.Identity.Name == "cascinabardellino@gmail.com")
                                        {
                                            <c><a href="@Url.Action("ImgRotateD", "Servizis", new { file = @item.Servizo_Id + "/" + @filename })" title="ruota immagine"> <span class="fa fa-undo"> </span> </a></c>
                                            <b><a href="@Url.Action("DeleteImg", "Servizis", new {id = item.Servizo_Id, file = @filename })" title="Cancella immagine"> X </a></b>
                                        }
                                    </span>
                                </div>
                            }
                        </div>

                    }
                }
                else
                {
                    if (immagini.Count() > 0)
                    {
                        <hr class="hr1" />
                        <span class="badge">@item.Servizio</span>
                        <div class="galla1">
                            @foreach (var immagine in immagini)
                            {
                                var filename = Path.GetFileName(immagine);
                                <div>
                                    <span>
                                        <a href="@Url.Content("~/Content/Immagini/Servizi/" + item.Servizo_Id + "/" + @filename)" data-lightbox="example-set"><img src="@Url.Content("~/Content/Immagini/Servizi/" + item.Servizo_Id +"/" + @filename)" alt="" /></a>
                                        @if (User.Identity.Name == "cascinabardellino@gmail.com")
                                        {
                                            <c><a href="@Url.Action("ImgRotateD", "Servizis", new { file = @item.Servizo_Id + "/" + @filename })" title="ruota immagine"> <span class="fa fa-undo"> </span> </a></c>
                                            <b><a href="@Url.Action("DeleteImg", "Servizis", new {id = item.Servizo_Id, file = @filename })" title="Cancella immagine"> X </a></b>
                                        }
                                    </span>
                                </div>
                            }
                        </div>

                    }
                }
            }

        </div>
                }
@*fine galleria servizi*@

@*Pulsante mobile*@
@if (Request.Browser.IsMobileDevice)
{
    <div class="mobile">
        <h1><a href="@Url.Action("EditImgCel", "Servizis")"><span class="fa fa-mobile fa-2x"></span></a></h1>
    </div>

}

Bardellino/Views/Servizis/Index.cshtml
@model IEnumerable<Bardellino.Models.Servizi>

@{
    ViewBag.Title = "Index";
}

<h2>Servizi</h2>
<div>
    <a href="@Url.Action("Create", "Servizis")" class="btn btn-primary"><span class="badge">@ViewBag.ServiziCount</span> Aggiungi</a>
    


</div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Servizio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descrizione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pubblica)
            </th>
            <th></th>
        </tr>

    </thead>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Servizio)
        </td>
        <td>
            @Html.Raw(item.Descrizione)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pubblica)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id=item.Servizo_Id }, new { @class = "fa fa-pencil-square-o fa-2x text-success", title="Modifica" })
            @Html.ActionLink(" ", "Delete", new { id=item.Servizo_Id }, new { @class = "fa fa-trash-o fa-2x text-danger", title = "Cancella" })
        </td>
    </tr>
}

</table>

Bardellino/Views/Servizis/IndexUt.cshtml
@model IEnumerable<Bardellino.Models.Servizi>

@{
    ViewBag.Title = "IndexUt";
}
<div class="jumboBardellino">
    @if (User.Identity.Name == "cascinabardellino@gmail.com")
    {
        <h3>
            <a href="@Url.Action("Create", "Servizis")" title="Gestone servizi"><span class="glyphicon glyphicon-plus-sign"></span> Aggiungi</a>
        </h3><hr />
    }
@using (Html.BeginForm("IndexUt", "Servizis", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="divServizi">
        @foreach (var item in Model)
        {
            if (User.Identity.Name == "cascinabardellino@gmail.com")
            {
                <a href="@Url.Action("Edit", "Servizis", new {id = item.Servizo_Id })" title="Testo"><span class="fa fa-pencil text-success pull-left h3"></span></a>
                    <a href="@Url.Action("EditImg", "Servizis", new {id = item.Servizo_Id })" title="Galleria"><span class="fa fa-camera text-primary pull-left h3"></span></a>
                    <a href="@Url.Action("EditImgP", "Servizis", new {id = item.Servizo_Id })" title="Logo"><span class="fa fa-picture-o text-warning pull-left h3"></span></a>
            }
               <a class="h2" role="button" data-toggle="collapse" href="#@item.Servizo_Id" aria-expanded="false" aria-controls="@item.Servizo_Id">
                    @if (File.Exists(Server.MapPath("~/Content/Immagini/Servizi/" + @item.Servizo_Id + ".jpg")))
                    {
                        <img class="img-thumbnail img-circle" src="@Url.Content("~/Content/Immagini/Servizi/" + @item.Servizo_Id + ".jpg")" />
                    }
                    @item.Servizio
                </a>
                <di class="collapse" id="@item.Servizo_Id">
                    <p>
                        @Html.ActionLink("Contattaci", "IndexUtMail", "Servizis", new { servizio = item.Servizio }, new { @class = "btn btn-bardellino btn-xs" })


                    </p>
                    <div class="galla1">
                        @Html.Raw(item.Descrizione)

                        @{
                            var immagini = Directory.GetFiles(Server.MapPath("/Content/Immagini/Servizi/" + @item.Servizo_Id + "/")).ToList();
                            foreach (var immagine in immagini)
                            {
                                var filename = Path.GetFileName(immagine);
                                <div style="padding:0px">
                                    <span>
                                        <a href="@Url.Content("~/Content/Immagini/Servizi/" + item.Servizo_Id +"/" + @filename)" data-lightbox="example-set" targhet="_blank"><img class="example-image" src="@Url.Content("~/Content/Immagini/Servizi/" + item.Servizo_Id +"/" + @filename)" alt="" /></a>
                                    </span>

                                </div>

                            }
                        }
                    </div>
                </di>
                <hr class="hr1" />

                            }
    </div>

                            }

</div>

Bardellino/Views/Servizis/IndexUtMail.cshtml
@model Bardellino.Models.ServiziMailViewModels

@{
    ViewBag.Title = "IndexUtMail";
}

<div class="jumboBardellino">
    <div class="divContatti">
        <h2>Richiesta informazioni</h2>
        <div class="row">
            <div class="col col-md-4">
                <p>
                    <address>
                        Cascina Bardellino<br />
                        Via Roma, 26 - Castel Gabbiano (CR)<br />
                        <abbr title="Phone">Tel:</abbr>
                        +39 0373 419535<br />
                        <abbr title="Cell">Cell:</abbr>
                        335 6943774/772
                    </address>
                    <address>
                        cascinabardellino@gmail.com<br />
                        <a href="mailto:cascinabardellino@gmail.com" title="cascinabardellino@gmail.com"><span class="fa fa-envelope-o fa-4x"></span></a>
                    </address>

                </p>
            </div>
            @using (Html.BeginForm("IndexUtMail", "Servizis", FormMethod.Post, new {servizio = @Request.QueryString["servizio"], @class = "form-horizontal", role = "form" }))
            {
                <div class="col col-md-8">
                    <form>
                        <div class="form-group">
                            <div class="col col-md-10">
                                <div class="alert alert-warning">
                                    <span class="h3">Richiesta informazioni per <strong>@Request.QueryString["servizio"]</strong></span>
                                    @Html.ValidationSummary("", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", @placeholder = "Il tuo nome" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Cognome, new { @class = "form-control", @placeholder = "Il tuo cognome" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "La tua mail" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Tel, new { @class = "form-control", @placeholder = "Telefono o cellulare" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.TextAreaFor(m => m.Messaggio, new { @class = "form-control", @placeholder = "Il tuo messaggio" })
                            </div>
                        </div>
                        <button type="submit" class="btn btn-bardellino">Invia messaggio</button>
                        @Html.ActionLink("Torna ai servizi", "IndexUt", "Servizis", new {@class="btn btn-success" })
                    </form>
                </div>

            }
        </div>

    </div>
</div>