Bardellino/Controllers/PromoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bardellino.Models;
using System.Web.Helpers;

namespace Bardellino.Controllers
{
    public class PromoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Promoes
        public ActionResult Index()
        {
            var promo = db.Promos.OrderBy(p=>p.DataI).ToList();
            ViewBag.PromoCount = promo.Count();
            return View(promo);
        }

        // GET: Promoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promo promo = db.Promos.Find(id);
            if (promo == null)
            {
                return HttpNotFound();
            }
            return View(promo);
        }

        // GET: Promoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Promoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Promo_Id,DataI,DataF,Nome,Attiva", Exclude ="Descrizione")] Promo promo)
        {
            FormCollection collection = new FormCollection(Request.Unvalidated().Form);
            promo.Descrizione = collection["Descrizione"];

            if (ModelState.IsValid)
            {
                db.Promos.Add(promo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(promo);
        }

        // GET: Promoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promo promo = db.Promos.Find(id);
            if (promo == null)
            {
                return HttpNotFound();
            }
            return View(promo);
        }

        // POST: Promoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Promo_Id,DataI,DataF,Nome,Attiva", Exclude = "Descrizione")] Promo promo)
        {
            FormCollection collection = new FormCollection(Request.Unvalidated().Form);
            promo.Descrizione = collection["Descrizione"];

            if (ModelState.IsValid)
            {
                db.Entry(promo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(promo);
        }

        // GET: Promoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promo promo = db.Promos.Find(id);
            if (promo == null)
            {
                return HttpNotFound();
            }
            return View(promo);
        }

        // POST: Promoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Promo promo = db.Promos.Find(id);
            db.Promos.Remove(promo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bardellino/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bardellino.Models;
using System.IO;
using System.Web.Helpers;

namespace Bardellino.Controllers
{
    public class SlidesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Slides
        public ActionResult Index()
        {
            return View(db.Slides.ToList());
        }

        // GET: Slides/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // GET: Slides/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Slides/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Slide_Id,Posizione,Testo,Immagine")] Slide slide, HttpPostedFileBase file)
        {
            if(file != null)
            {
                int num = db.Slides.OrderByDescending(u => u.Posizione).Select(s=>s.Posizione).FirstOrDefault();
                int nuovo = num + 1;
                slide.Immagine = nuovo + ".jpg";
                slide.Posizione =nuovo;
                if (ModelState.IsValid)
                {
                    if (file != null)
                    { 
                        try
                        {
                        var path = Path.Combine(Server.MapPath("~/Content/Immagini/Slide/"), nuovo + ".jpg");
                            WebImage img = new WebImage(file.InputStream);
                            var larghezza = img.Width;
                            var altezza = img.Height;
                            var rapportoO = larghezza / altezza;
                            var rapportoV = altezza / larghezza;
                            if (altezza > 1900 | larghezza > 1900)
                            {
                                if (rapportoO >= 1)
                                {
                                    ViewBag.Message = "Attendi la fine del download...";
                                    img.Resize(1900, 1900 / rapportoO);
                                    img.Save(path);
                                    ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                                }
                                else
                                {
                                    img.Resize(800 / rapportoV, 800);
                                    img.Save(path);
                                    ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                                }
                            }
                            else
                            {
                                if (rapportoO >= 1)
                                {
                                    ViewBag.Message = "Attendi la fine del download...";
                                    img.Save(path);
                                    ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                                }
                                else
                                {
                                    ViewBag.Message = "Attendi la fine del download...";
                                    img.Save(path);
                                    ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        }
                        db.Slides.Add(slide);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }
           else
            {
                ViewBag.Message = "Devi scegliere un file";
            }

            return View(slide);
        }

        // GET: Slides/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: Slides/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Slide_Id,Posizione,Testo,Immagine")] Slide slide, HttpPostedFileBase file)
        {
            if(file != null)
            {
                try
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Immagini/Slide/"), slide.Immagine);
                    WebImage img = new WebImage(file.InputStream);
                    var larghezza = img.Width;
                    var altezza = img.Height;
                    var rapportoO = larghezza / altezza;
                    var rapportoV = altezza / larghezza;
                    if (altezza > 1900 | larghezza > 1900)
                    {
                        if (rapportoO >= 1)
                        {
                            ViewBag.Message = "Attendi la fine del download...";
                            img.Resize(1900, 1900 / rapportoO);
                            img.Save(path);
                            ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                        }
                        else
                        {
                            img.Resize(800 / rapportoV, 800);
                            img.Save(path);
                            ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                        }
                    }
                    else
                    {
                        if (rapportoO >= 1)
                        {
                            ViewBag.Message = "Attendi la fine del download...";
                            img.Save(path);
                            ViewBag.Message = "Download immagine orizzontale avvenuto con successo. Dimensione immagine originale: larghezza " + larghezza + " Altezza " + altezza;
                        }
                        else
                        {
                            ViewBag.Message = "Attendi la fine del download...";
                            img.Save(path);
                            ViewBag.Message = "Download immagine verticale avvenuto con successo. Dimensione immagine: larghezza " + larghezza + "Altezza" + altezza;
                        }
                    }


                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(slide).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slide);
        }

        // GET: Slides/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: Slides/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slide slide = db.Slides.Find(id);
            var path = Path.Combine(Server.MapPath("~/Content/Immagini/Slide/"), slide.Immagine);
            System.IO.File.Delete(path);
            db.Slides.Remove(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bardellino/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/moment-with-locales.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*Menu di navigazione*@
    <div class="navbar navbar-default navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cascina Bardellino", "Index", "Home", new { area = "" }, new { @class = "navbar-brand header-logo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dove siamo", "Dove", "Home")</li>
                    <li>@Html.ActionLink("Contatti", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Galleria", "Galleria", "Servizis")</li>
                    <li>@Html.ActionLink("Servizi", "IndexUt", "Servizis")</li>
                    @if (User.Identity.Name == ("cascinabardellino@gmail.com"))
                    {
                        <li>@Html.ActionLink(" Promo", "Index", "Promoes", null, new {@class= "fa fa-google-wallet", title ="Gestione promo" })</li>
                        <li>@Html.ActionLink(" Sfondi", "Index", "Slides", null, new { @class = "fa fa-picture-o", title = "Gestione sfondi" })</li>
                    }
                </ul>
                <ul class="nav navbar-collapse navbar-right">
                    <li class="h3">@Html.Partial("_LoginPartial")
                    </li>
                </ul>
            </div>
    </div>
    <div class="body-content">
        <img class="ImgBody" src="@Url.Content("~/Content/Immagini/" + @ViewBag.Title + ".jpg")" />
        @RenderBody()
        <footer class="navbar-fixed-bottom">
            <p>
              @Html.Partial("_LoginPartial")  &copy; @DateTime.Now.Year - Cascina Bardellino
            </p>
        </footer>
    </div>
    @*Fine menu navigazione*@
    @*Social laterale destra*@

    <div class="docu">
        <p>
            <a href="#nogo" id="xdocu" title="Social"><span class="glyphicon glyphicon-remove text-danger"></span></a><br />
        </p>
            <ul>
                <li>
                    <a href="https://www.facebook.com/letuecerimonie" target="_blank" title="Seguici su Facebook">
                        <img src="~/Content/Immagini/fb.png" />
                    </a>

                </li>
            </ul>
            <ul>
                <li>
                    <a href="https://www.instagram.com/cascina.bardellino/" target="_blank" title="Seguici su Instagram">
                        <img src="~/Content/Immagini/Instagram.png" />
                    </a>

                </li>
            </ul>
        <ul>
            <li>
                <a href="https://www.matrimonio.com/ristoranti-ricevimenti/cascina-bardellino--e105767/" target="_blank" title="Siamo su matrimonio.com">
                    <img src="~/Content/Immagini/Mat.png" />
                </a>

            </li>
        </ul>
   </div>

    @*Fine Socal laterale destra*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $('#bt').mouseover((function () {
            $('[data-toggle="tooltip"]').tooltip()
        }));
        $('#xdocu').click(function () {
            $('.docu ul li').toggle('normal');
        });
    </script>
</body>
</html>